var mongoose = require("mongoose");
var Schema = mongoose.Schema;
const ObjectId = Schema.Types.ObjectId;

var AireSchema = new Schema({
  _id: { type: ObjectId, auto: true },
  provincia: { type: Number, required: true },
  municipio: { type: Number, required: true },
  estacion: { type: Number, required: true },
  magnitud: { type: Number, required: true },
  punto_muestreo: { type: String, required: true },
  ano: { type: Number, required: true },
  mes: { type: Number, required: true },
  dia: { type: Number, required: true },
  H01: { type: Number },
  V01: { type: String },
  H02: { type: Number },
  V02: { type: String },
  H03: { type: Number },
  V03: { type: String },
  H04: { type: Number },
  V04: { type: String },
  H05: { type: Number },
  V05: { type: String },
  H06: { type: Number },
  V06: { type: String },
  H07: { type: Number },
  V07: { type: String },
  H08: { type: Number },
  V08: { type: String },
  H09: { type: Number },
  V09: { type: String },
  H10: { type: Number },
  V10: { type: String },
  H11: { type: Number },
  V11: { type: String },
  H12: { type: Number },
  V12: { type: String },
  H13: { type: Number },
  V13: { type: String },
  H14: { type: Number },
  V14: { type: String },
  H15: { type: Number },
  V15: { type: String },
  H16: { type: Number },
  V16: { type: String },
  H17: { type: Number },
  V17: { type: String },
  H18: { type: Number },
  V18: { type: String },
  H19: { type: Number },
  V19: { type: String },
  H20: { type: Number },
  V20: { type: String },
  H21: { type: Number },
  V21: { type: String },
  H22: { type: Number },
  V22: { type: String },
  H23: { type: Number },
  V23: { type: String },
  H24: { type: Number },
  V24: { type: String }
});

module.exports = mongoose.model("Aire", AireSchema);